// clubsList.ts

const clubsList: string[] = [
    "AIESEC in Queen’s",
    "All the Queen’s Men",
    "ALS Queen’s",
    "Arab Students’ Association at Queen’s University",
    "Association of Indian Graduate Students at Queen’s",
    "Autism Speaks Canada Student Association at Queen’s",
    "Bader Lane Productions",
    "Cam’s Kids",
    "Campus Life",
    "Canadian Association for Research in Regenerative Medicine at Queen’s",
    "Canadian Undergraduate Conference on Healthcare",
    "Canadian Army Reserve - Princess of Wales’ Own Regiment",
    "Canterbury Club",
    "Canvas n Care",
    "Cardano at Queen’s University",
    "Care Home Pen Pals",
    "Chess and Health",
    "Chinese International Volunteer Organization",
    "Consensual Humans",
    "Conservation Queen’s",
    "Egyptian Students Association at Queen’s (ESAQ)",
    "Enactus Queen’s",
    "Exhibit Change",
    "Focus Film Festival",
    "FreshSight Queen’s Consulting",
    "Friday Friends",
    "GetREAL Queen’s",
    "GirlupQueens",
    "Global Literature: Influences of the Decades",
    "Global Society for Genetics and Genome Biology",
    "Good Mourning Queen’s",
    "Google Developer Student Club",
    "Grandfriends",
    "Greenovations",
    "Heart 4 Heart Queen’s Chapter",
    "Her Campus",
    "Hiel Fellowship",
    "HOSA Queen’s",
    "Innocence Queen’s",
    "Inquire Publication",
    "Iranian Association of Queen’s University",
    "Islamic Relief at Queen’s University (IRQU)",
    "Jack.org",
    "Jam for Justice Queen’s",
    "Japanese Relations at Queen’s",
    "Kingston Asian Christian Fellowship (KACF)",
    "Kingston Gets Active Ambassadors",
    "Kingston Hidden Artist Collective",
    "Let’s Talk Science",
    "Levana Gender Advocacy Centre (LGAC)",
    "Medsupply Ukraine",
    "Momentum Vocal Group",
    "Mosaic",
    "MUSE Magazine",
    "MusicBox Children’s Charity – Queen’s Chapter",
    "NeuGeneration",
    "Newman House Catholic Club",
    "Nyantende Foundation",
    "On The Same Page at Queen’s",
    "Operation Smile Queen’s",
    "Orthodox Christian Student Association (OCSA)",
    "Oxfam at Queen’s",
    "Pakistani Student’s Association",
    "Perspectives on Gender, Equity, and Politics",
    "Poco a Poco",
    "Power to Change Queen’s",
    "Project Happiness Queen’s",
    "Qapsule",
    "QC-IDEAS",
    "QHacks",
    "QLANG (Queen’s Languages and Linguistics Club)",
    "QRPGS",
    "QMIND",
    "QSALSA (QueensU Spanish and Latin-American Students’ Association)",
    "Qtaku: Queen’s Anime Club",
    "QU Glow",
    "QU in Support of Red Cross",
    "QUCraft",
    "Queen’s 4 Paws",
    "Queen’s Actuarial Club (QAC)",
    "Queen’s American Sign Language Club",
    "Queen’s Amnesty International",
    "Queen’s Amtgard",
    "Queen’s Applied Biotechnology",
    "Queen’s Armenian Students’ Association",
    "Queen’s Asian Students’ Association",
    "Queen’s Association of Korean Canadian Scientists and Engineers (Queen’s AKCSE)",
    "Queen’s Astronomy Club",
    "Queen’s Backing Action on the Climate Crisis",
    "Queen’s Baja SAE Design Team",
    "Queen’s Bands",
    "Queen’s Beauty & Wellness Industry Connection",
    "Queen’s Bioinformatics Club",
    "Queen’s Biomedical Innovation Team",
    "Queen’s Black Fashion Association",
    "QU BLOOM",
    "Queen’s Board Game Club",
    "Queen’s Bridge Building Team",
    "Queen’s Bucket Listers",
    "Queen’s Business Brigades",
    "Queen’s Business Law Journal",
    "Queen’s Camp Outlook",
    "Queen’s Capes for Kids",
    "Queen’s Capital",
    "Queen’s Cardiac Research Committee",
    "Queen’s Chess Club",
    "Queen’s Chinese Students and Scholars Associations",
    "Queen’s CODE",
    "Queen’s Concussion Awareness Committee",
    "Queen’s Conference in Business and Governance (QCBG)",
    "Queen’s Conference on Business and Mining",
    "Queen’s Conference on Education (QCE)",
    "Queen’s Conference on Ocean Sustainability",
    "Queen’s Correctional Services Volunteers",
    "Queen’s Cultural Exchange",
    "Queen’s Dads Clash of Clans",
    "Queen’s Data Analytics Association",
    "Queen’s Debating Union",
    "Queen’s Economics Society (QES)",
    "Queen’s Fashion Industry Network",
    "Queen’s Feminist Collective",
    "Queen’s Feminist Leadership in Politics QFLIP",
    "Queen’s Film Appreciation Club",
    "Queen’s First Aid",
    "Queen’s for Campfire Circle",
    "Queen’s for Parkinson’s Kingston",
    "Queen’s for Sustainable Fashion",
    "Queen’s for the Community",
    "Queen’s French Club",
    "Queen’s Friends of MSF",
    "Queen’s Game Development Club",
    "Queen’s Genetically Engineered Machine",
    "Queen’s Global Biomedical Design Conference",
    "Queen’s Graduate Management Consulting Association",
    "Queen’s HanVoice",
    "Queen’s Health and Nutrition Society (QHNS)",
    "Queen’s Health Outreach",
    "Queen’s Healthcare and Business Conference (QHBC)",
    "Queen’s Hellenic Students’ Association",
    "Queen’s Hillel",
    "Queen’s Hong Kong Students’ Association",
    "Queen’s Hyperloop Design Team",
    "Queen’s Indian Student’s Association Dance Team (QISA DT)",
    "Queen’s InSight",
    "Queen’s Institute of Healthcare Improvement",
    "Queen’s International Affairs Association",
    "Queen’s Juggling Club",
    "Queen’s Kaleidoscope",
    "Queen’s Kidney Club",
    "Queen’s Korean Student Association",
    "Queen’s Ladies in Fitness Training (QLIFT)",
    "Queen’s Little Forests Kingston",
    "Queen’s Living Water Mandarin Christian Fellowship",
    "Queen’s Love146",
    "Queen’s Lyme Disease Coalition Madoc’s Chapter",
    "Queen’s Medical Equipment Redistribution Collaboration Initiative (MERCI)",
    "Queen’s MEDLIFE",
    "Queen’s Miracle Babies",
    "Queen’s Mully Children’s Family",
    "Queen’s Music Club",
    "Queen’s Musical Theatre",
    "Queen’s Native Student Association (QNSA)",
    "Queen’s Ovarian Cancer Club",
    "Queen’s Period",
    "Queen’s Pharmaceutical Sciences Club",
    "Queen’s Pinoy Association",
    "Queen’s Players",
    "Queen’s Pre-Dental Society",
    "Queen’s Pre-Law Society",
    "Queen’s Pre-Medical Society",
    "Queen’s Project on International Development (QPID)",
    "Queen’s Project Red",
    "Queen’s Project Sunshine",
    "Queen’s Protects Animal Welfare Society (QPAWS)",
    "Queen’s Punjabi Student Association",
    "Queens Quantum Computing Club",
    "Queen’s Racing Formula SAE Team",
    "Queen’s Relay For Life",
    "Queen’s Rocket Engineering Team",
    "Queen’s Shinerama",
    "Queen’s Sikh Student Association",
    "Queen’s Soul Food",
    "Queen’s South Asian Association",
    "Queen’s Space Engineering Team",
    "Queen’s Spirituality & Wellness",
    "Queen’s Sports Analytics Organization",
    "Queen’s Startup Consulting",
    "Queen’s Startup Summit",
    "Queen’s Student Diversity Project",
    "Queen’s Student Investors Group",
    "Queen’s Students for Literacy",
    "Queen’s Students for Partners in Health Canada",
    "Queen’s Swing Dance Club",
    "Queen’s Tamil Students’ Association",
    "Queen’s Television",
    "Queen’s Tissue and Organ Donor Advocates (QTODA)",
    "Queen’s Trading Committee",
    "Queen’s Undergraduate Conference in Literature",
    "Queen’s University Algorithmic Network Trading Team",
    "Queen’s University Best Buddies",
    "Queen’s University Blood Team",
    "Queen’s University Business and Engineering",
    "Queen’s University Canadian Association for Global Health (CAGH) Student Chapter",
    "Queen’s University Children’s Health Association",
    "Queen’s University Chorus",
    "Queen’s University Concert Orchestra (QUCO)",
    "Queen’s University Dance Marathon",
    "Queen’s University Liberal Association (QULA)",
    "Queen’s University Taylor Swift Society",
    "Queen’s Vets Without Borders",
    "Queen’s Vietnamese Students’ Association",
    "Queen’s Web Development Club",
    "Queen’s Women in Financial Markets",
    "Queen’s Women in Leadership",
    "Queen’s Women of Colour Collective",
    "Young Caregivers Community",
    "Queen’s Yu Chinese Modern and Contemporary Theatre Society",
    "Queens Advocates For Women’s Global Rights",
    "Queens Awareness of Bladder Cancer",
    "Queens Business and Artificial Intelligence",
    "Queens for the Boys",
    "Queens Medical Brigades",
    "Queens Model Parliament",
    "Queens Muslim Student Association",
    "Queens University Quiz Team",
    "Queens University Ukrainian Student’s Association (QUUSA)",
    "Queens Vision Society",
    "QuGujarat",
    "Quilt",
    "QWave",
    "QWPLS",
    "Raise The Bar Queen’s",
    "ReQap",
    "Robogals Queen’s",
    "Russian and Eastern European Studies Society",
    "Save the Mothers: Queen’s University Chapter",
    "Science to Business Network (S2BN) Kingston Chapter",
    "Search for the Cure",
    "Senior Symphonies",
    "Smith Black Business Association",
    "SSAQU",
    "Starts With Youth",
    "Step Above Stigma Queen’s",
    "Students 4 Special Olympics",
    "Students at Queen’s Urban Agriculture and Sustainability Hub (SQUASH)",
    "Students for Wishes",
    "Sustainable Development Goals Hub",
    "SWAM Kingston",
    "TEDxQueensU",
    "Telephone Aid Line Kingston",
    "Thaqalayn Muslim Association (TMA)",
    "The Caledonias",
    "The Earth Centre",
    "The Great Panda Society",
    "The Greener Project",
    "The Lilac Project",
    "The Mental Health Awareness Committee",
    "The Nourishment Project",
    "The Shoebox Project x Queen’s",
    "Thomistic Institute",
    "Trillers A Cappella",
    "Ultraviolet Magazine",
    "UNICEF Queen’s",
    "Vogue Charity Fashion Show",
    "WebStraw at Queen’s University",
    "Women in International Security Queen’s (WIIS-Queen’s)",
    "Women in Science and Engineering (WISE) Queen’s",
    "Women of Colour Collective",
    "Y2K: The Millennium Project",
    "Youth Climate Hub at Queen’s",
    "Youth Homelessness Queen’s",
    "Youth Opt for Change",
    "Zahra Foundation",
    "Working - Part Time",
  ];
  
  export default clubsList;
  